FROM ubuntu:20.04

RUN apt update && apt install -y ansible
RUN mkdir -p /ansible-plays/

WORKDIR /
COPY ./playbook.yml ./ansible-plays/
COPY ./ansible-plex/ /etc/ansible/roles/ansible-plex/

# Run the play (CAN BE OVERIDDEN)
CMD [ "ansible-playbook", "./ansible-plays/playbook.yml" ]