---
# tasks file for ansible-plex

- name: Create plex group
  group:
    name: plex
    state: present
- name: Create plex user
  user:
    name: plex
    group: plex
    append: yes

- name: Include ubuntu specific tasks
  include_tasks: "ubuntu.yml"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Include storage tasks
  include_tasks: "storage.yml"