---
# Ubuntu specific installation for plex server

- name: Make sure apt repos are up-to-date
  apt:
    name: '*'
    state: latest
- name: Add plex GPG key
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present
- name: Add the plex repository to sources (for later updating with apt)
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present
    filename: plexmediaserver
- name: Update from newly added sources
  apt:
    name: '*'
    state: latest
- name: Install Nginx (reverse-proxy)
  apt:
    name: nginx
    state: present
- name: Install Plex from Deb Package
  apt:
    deb: https://downloads.plex.tv/plex-media-server-new/1.20.3.3483-211702a9f/debian/plexmediaserver_{{ plex_version }}.deb
- name: Copy reverse proxy nginx.conf
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/nginx.conf
    owner: "{{ nginx.owner }}"
    group: "{{ nginx.group }}"
    mode: "770"
    follow: true
- name: Restart services
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - plexmediaserver
    - nginx
- name: Ensure services are enabled on restart
  systemd:
    name: "{{ item }}"
    enabled: true
  with_items:
    - plexmediaserver
    - nginx